# -------------------------------------
# Setup
# -------------------------------------
mysql_vendor: "mariadb"
mysql_root_password: 'change_me_NOW'

# -------------------------------------
# Configuration
# -------------------------------------
mysql_cnf: []


# -------------------------------------
# MariaDB
# -------------------------------------
mariadb_version: '10.1' # (5.5, 10.0, 10.1)
# See: http://mariadb.org/mariadb/repositories/
mariadb_repository: "http://ftp.igh.cnrs.fr/pub/mariadb/repo/{{ mariadb_version }}/debian"

# -------------------------------------
# Percona
# -------------------------------------
percona_version: '5.6'
percona_repository: 'http://repo.percona.com/apt'
