---

- name: APT | Add Debian repository
  apt_repository: repo='deb http://{{ apt_default_host }}/debian jessie main contrib non-free' state=present

- name: APT | Install PHP related packages
  apt: pkg={{ item }} state=latest
  with_items:
    - ant
    - libgettext-ant-tasks-java
    - php-codesniffer

- name: APT | Install PHP related packages (backports)
  apt: pkg={{ item }} state=latest default_release=wheezy-backports
  with_items:
    - phpunit

- name: APT | Install PHP related packages (jessie / testing)
  apt: pkg={{ item }} state=latest default_release=jessie
  with_items:
    - pdepend
    - phpcpd
    - phploc
    - phpmd
