redis_config:
  daemonize: 'yes'
  pidfile: '/var/run/redis/redis-server.pid'
  port: '6379'
  bind: '127.0.0.1'
  timeout: '0'
  tcp_keepalive: '0'
  loglevel: 'notice'
  logfile: '/var/log/redis/redis-server.log'
  databases: '16'
  save:
    - '900 1'
    - '300 10'
    - '60 10000'
  stop_writes_on_bgsave_error: 'yes'
  rdbcompression: 'yes'
  rdbchecksum: 'yes'
  dbfilename: 'dump.rdb'
  dir: '/var/lib/redis'
  slave_serve_stale_data: 'yes'
  slave_read_only: 'yes'
  repl_disable_tcp_nodelay: 'no'
  slave_priority: '100'
  appendonly: 'no'
  appendfsync: 'everysec'
  no_appendfsync_on_rewrite: 'no'
  auto_aof_rewrite_percentage: '100'
  auto_aof_rewrite_min_size: '64mb'
  lua_time_limit: '5000'
  slowlog_log_slower_than: '10000'
  slowlog_max_len: '128'
  hash_max_ziplist_entries: '512'
  hash_max_ziplist_value: '64'
  list_max_ziplist_entries: '512'
  list_max_ziplist_value: '64'
  set_max_intset_entries: '512'
  zset_max_ziplist_entries: '128'
  zset_max_ziplist_value: '64'
  activerehashing: 'yes'
  client_output_buffer_limit: 'normal 0 0 0'
  client_output_buffer_limit1: 'slave 256mb 64mb 60'
  client_output_buffer_limit2: 'pubsub 32mb 8mb 60'
  hz: '10'
  aof_rewrite_incremental_fsync: 'yes'
