---

- name: APT | Install fail2ban 
  apt: update_cache=yes cache_valid_time=3600 pkg=fail2ban state=latest
  notify: restart fail2ban

- name: TEMPLATE | Deploy /etc/default/fail2ban
  template: src=etc/default/fail2ban.j2 dest=/etc/default/fail2ban
  notify: restart fail2ban

- name: TEMPLATE | Deploy /etc/fail2ban/fail2ban.conf
  template: src=etc/fail2ban/fail2ban.conf.j2 dest=/etc/fail2ban/fail2ban.conf
  notify: restart fail2ban

- name: TEMPLATE | Deploy /etc/fail2ban/jail.conf
  template: src=etc/fail2ban/jail.conf.j2 dest=/etc/fail2ban/jail.conf
  notify: restart fail2ban

