---
- name: FAIL | Check parameters
  fail: msg='Bad parmeters php_fpm_socket == unix | tcp'
  when: php_fpm_socket != 'unix' and php_fpm_socket != 'tcp' 

- name: APT | Install php packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-geoip
    - php5-mcrypt
    - php5-mysqlnd 
    - php5-intl
    - php5-dev

- name: APT | Install php packages (specific Dotdeb)
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-readline
    - php5-redis
  when: use_dotdeb is defined and use_dotdeb

- name: APT | Install php-apcu (PHP 5.5+ only)
  apt: pkg=php5-apcu state=latest
  when: use_dotdeb is defined and use_dotdeb and dotdeb_php_version|version_compare('5.5', operator='ge', strict=True)

- name: APT | Install php-apc (PHP 5.4 max only)
  apt: pkg=php5-apcu state=latest
  when: use_dotdeb is defined and use_dotdeb and dotdeb_php_version|version_compare('5.5', operator='lt', strict=True)

- name: TEMPLATE | Deploy PHP configuration file
  template: src=php.ini.j2 dest=/etc/php5/fpm/php.ini owner=root mode=0644
  notify: restart php-fpm

# Bug! APCu with PHP 5.5+
- name: TEMPLATE | Deploy module configurations
  template: src=mods-available/{{ item }}.j2 dest=/etc/php5/mods-available/{{ item }} owner=root mode=0644
  with_items:
    - apcu.ini 
  notify: restart php-fpm

- name: INCLUDE | PHP-FPM socket type
  include: fpm_unix_socket.yml
  when: php_fpm_socket == 'unix'
