fail2ban_opts: ''
fail2ban_definition:
  loglevel: 3
  logtarget: '/var/log/fail2ban.log'
  socket: '/var/run/fail2ban/fail2ban.sock'
  pidfile: '/var/run/fail2ban/fail2ban.pid'
fail2ban_default:
  ignoreip:
    - '127.0.0.1/8'
  bantime: '600'
  findtime: '600'
  maxretry: '3'
  backend: 'auto'
  usedns: 'warn'
  destemail: 'root@localhost'
  sendername: 'Fail2ban'
  banaction: 'iptables-multiport'
  mta: 'sendmail'
  protocol: 'tcp'
fail2ban_jails:
  - section: 'asterisk-udp'
    enabled: 'false'
    logpath: '/var/log/asterisk/messages'
    filter: 'asterisk'
    port: '5060,5061'
    protocol: 'udp'
  - section: 'pure-ftpd'
    filter: 'pure-ftpd'
    maxretry: '6'
    port: 'ftp,ftp-data,ftps,ftps-data'
    logpath: '/var/log/syslog'
    enabled: 'false'
  - section: 'lighttpd-fastcgi'
    filter: 'lighttpd-fastcgi'
    port: 'http,https'
    enabled: 'false'
    logpath: '/var/log/lighttpd/error.log'
  - section: 'ssh-iptables-ipset6'
    maxretry: '6'
    filter: 'sshd'
    port: 'ssh'
    banaction: 'iptables-ipset-proto6'
    enabled: 'false'
    logpath: '/var/log/sshd.log'
  - section: 'apache'
    logpath: '/var/log/apache*/*error.log'
    enabled: 'false'
    filter: 'apache-auth'
    maxretry: '6'
    port: 'http,https'
  - section: 'roundcube-auth'
    port: 'http,https'
    filter: 'roundcube-auth'
    enabled: 'false'
    logpath: '/var/log/roundcube/userlogins'
  - section: 'lighttpd-auth'
    filter: 'suhosin'
    port: 'http,https'
    logpath: '/var/log/lighttpd/error.log'
    enabled: 'false'
  - section: 'sasl'
    enabled: 'false'
    logpath: '/var/log/mail.log'
    port: 'smtp,ssmtp,submission,imap2,imap3,imaps,pop3,pop3s'
    filter: 'postfix-sasl'
  - section: 'nginx-http-auth'
    enabled: 'false'
    logpath: '/var/log/nginx/error.log'
    filter: 'nginx-http-auth'
    port: 'http,https'
  - section: 'ssh-iptables-ipset4'
    enabled: 'false'
    logpath: '/var/log/sshd.log'
    maxretry: '6'
    filter: 'sshd'
    port: 'ssh'
    banaction: 'iptables-ipset-proto4'
  - section: 'ssh'
    logpath: '/var/log/auth.log'
    enabled: 'true'
    port: 'ssh'
    filter: 'sshd'
    maxretry: '6'
  - section: 'pam-generic'
    maxretry: '6'
    filter: 'pam-generic'
    port: 'anyport'
    banaction: 'iptables-allports'
    enabled: 'false'
    logpath: '/var/log/auth.log'
  - section: 'asterisk-tcp'
    enabled: 'false'
    logpath: '/var/log/asterisk/messages'
    port: '5060,5061'
    protocol: 'tcp'
    filter: 'asterisk'
  - section: 'couriersmtp'
    enabled: 'false'
    logpath: '/var/log/mail.log'
    filter: 'couriersmtp'
    port: 'smtp,ssmtp,submission'
  - section: 'apache-multiport'
    port: 'http,https'
    maxretry: '6'
    filter: 'apache-auth'
    enabled: 'false'
    logpath: '/var/log/apache*/*error.log'
  - section: 'proftpd'
    port: 'ftp,ftp-data,ftps,ftps-data'
    filter: 'proftpd'
    maxretry: '6'
    logpath: '/var/log/proftpd/proftpd.log'
    enabled: 'false'
  - section: 'postfix'
    enabled: 'false'
    logpath: '/var/log/mail.log'
    port: 'smtp,ssmtp,submission'
    filter: 'postfix'
  - section: 'mysqld-auth'
    port: '3306'
    filter: 'mysqld-auth'
    enabled: 'false'
    logpath: '/var/log/mysqld.log'
  - section: 'sogo-auth'
    filter: 'sogo-auth'
    port: 'http, https'
    enabled: 'false'
    logpath: '/var/log/sogo/sogo.log'
  - section: 'xinetd-fail'
    logpath: '/var/log/daemon.log'
    enabled: 'false'
    filter: 'xinetd-fail'
    maxretry: '2'
    port: 'all'
    banaction: 'iptables-multiport-log'
  - section: 'named-refused-tcp'
    protocol: 'tcp'
    port: 'domain,953'
    filter: 'named-refused'
    logpath: '/var/log/named/security.log'
    enabled: 'false'
  - section: 'wuftpd'
    enabled: 'false'
    logpath: '/var/log/syslog'
    maxretry: '6'
    filter: 'wuftpd'
    port: 'ftp,ftp-data,ftps,ftps-data'
  - section: 'php-url-fopen'
    enabled: 'false'
    logpath: '/var/www/*/logs/access_log'
    port: 'http,https'
    filter: 'php-url-fopen'
  - section: 'apache-noscript'
    enabled: 'false'
    logpath: '/var/log/apache*/*error.log'
    port: 'http,https'
    maxretry: '6'
    filter: 'apache-noscript'
  - section: 'ssh-ddos'
    logpath: '/var/log/auth.log'
    enabled: 'false'
    port: 'ssh'
    filter: 'sshd-ddos'
    maxretry: '6'
  - section: 'dovecot'
    port: 'smtp,ssmtp,submission,imap2,imap3,imaps,pop3,pop3s'
    filter: 'dovecot'
    enabled: 'false'
    logpath: '/var/log/mail.log'
  - section: 'apache-overflows'
    port: 'http,https'
    filter: 'apache-overflows'
    maxretry: '2'
    logpath: '/var/log/apache*/*error.log'
    enabled: 'false'
  - section: 'dropbear'
    filter: 'dropbear'
    maxretry: '6'
    port: 'ssh'
    logpath: '/var/log/auth.log'
    enabled: 'false'
  - section: 'courierauth'
    logpath: '/var/log/mail.log'
    enabled: 'false'
    filter: 'courierlogin'
    port: 'smtp,ssmtp,submission,imap2,imap3,imaps,pop3,pop3s'
  - section: 'ssh-route'
    maxretry: '6'
    filter: 'sshd'
    enabled: 'false'
    action: 'route'
    logpath: '/var/log/sshd.log'
  - section: 'vsftpd'
    enabled: 'false'
    logpath: '/var/log/vsftpd.log'
    port: 'ftp,ftp-data,ftps,ftps-data'
    maxretry: '6'
    filter: 'vsftpd'
